"""15 AC state presets for Hisense air conditioner."""
PRESETS = [
    {"name": "关机", "codeId": "hisense_power_off_v1",
     "power": "off", "mode": "cool", "temp": "24", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "unknown", "swingH": "unknown"},
    {"name": "制冷24℃ 超强风 上下扫风", "codeId": "hisense_cool_24_turbo_swingV_v1",
     "power": "on", "mode": "cool", "temp": "24", "fan": "turbo",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "on", "swingH": "unknown"},
    {"name": "制冷20℃ 超强风 上下扫风", "codeId": "hisense_cool_20_turbo_swingV_v1",
     "power": "on", "mode": "cool", "temp": "20", "fan": "turbo",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "on", "swingH": "unknown"},
    {"name": "制冷25℃ 自动风", "codeId": "hisense_cool_25_auto_v1",
     "power": "on", "mode": "cool", "temp": "25", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "unknown", "swingH": "unknown"},
    {"name": "制冷26℃ 自动风", "codeId": "hisense_cool_26_auto_v1",
     "power": "on", "mode": "cool", "temp": "26", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "unknown", "swingH": "unknown"},
    {"name": "制冷27℃ 自动风", "codeId": "hisense_cool_27_auto_v1",
     "power": "on", "mode": "cool", "temp": "27", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "unknown", "swingH": "unknown"},
    {"name": "制冷28℃ 自动风", "codeId": "hisense_cool_28_auto_v1",
     "power": "on", "mode": "cool", "temp": "28", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "unknown", "swingH": "unknown"},
    {"name": "制冷24℃ 强力", "codeId": "hisense_cool_24_turbo_v1",
     "power": "on", "mode": "cool", "temp": "24", "fan": "auto",
     "turbo": True, "quiet": False, "sleep": False,
     "swingV": "unknown", "swingH": "unknown"},
    {"name": "制冷24℃ 上下扫风", "codeId": "hisense_cool_24_swingV_v1",
     "power": "on", "mode": "cool", "temp": "24", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "on", "swingH": "unknown"},
    {"name": "制冷24℃ 左右扫风", "codeId": "hisense_cool_24_swingH_v1",
     "power": "on", "mode": "cool", "temp": "24", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "unknown", "swingH": "on"},
    {"name": "除湿24℃", "codeId": "hisense_dry_24_v1",
     "power": "on", "mode": "dry", "temp": "24", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "unknown", "swingH": "unknown"},
    {"name": "送风", "codeId": "hisense_fan_v1",
     "power": "on", "mode": "fan", "temp": "N/A", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "unknown", "swingH": "unknown"},
    {"name": "制热24℃", "codeId": "hisense_heat_24_v1",
     "power": "on", "mode": "heat", "temp": "24", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "unknown", "swingH": "unknown"},
    {"name": "制热26℃", "codeId": "hisense_heat_26_v1",
     "power": "on", "mode": "heat", "temp": "26", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "unknown", "swingH": "unknown"},
    {"name": "睡眠", "codeId": "hisense_sleep_v1",
     "power": "on", "mode": "cool", "temp": "24", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": True,
     "swingV": "unknown", "swingH": "unknown"},
]
