<#
.SYNOPSIS
    Make the two repository libraries visible to the Arduino IDE / arduino-cli.

.DESCRIPTION
    The Arduino IDE only looks for libraries inside your sketchbook
    (<sketchbook>\libraries). This repository keeps a single authoritative copy
    of each library:

      firmware\shared\RemoteACCore          Arduino library layout already
      firmware\agent-platformio\lib\srun-c  PlatformIO layout (include\ + src\)

    RemoteACCore is installed as a directory junction (no administrator rights
    required), so editing the repository - for example dropping your own
    config\profiles\xidian.h - is picked up immediately.
    srun-c must be flattened into a single src\ directory because arduino-cli
    does not understand the PlatformIO include\ + src\ split, so it is
    generated. Re-run this script after changing anything under lib\srun-c.

.PARAMETER Sketchbook
    Sketchbook root. Defaults to $env:ARDUINO_SKETCHBOOK, then
    <Documents>\Arduino.

.EXAMPLE
    ./firmware/arduino-ide/tools/install-arduino-libraries.ps1

.NOTES
    This script never touches credentials, never compiles, never flashes.
#>
[CmdletBinding()]
param(
    [string]$Sketchbook
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$RepoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..\..\..')).Path

if (-not $Sketchbook) {
    if ($env:ARDUINO_SKETCHBOOK) {
        $Sketchbook = $env:ARDUINO_SKETCHBOOK
    } else {
        $Sketchbook = Join-Path ([Environment]::GetFolderPath('MyDocuments')) 'Arduino'
    }
}
$LibDir = Join-Path $Sketchbook 'libraries'
New-Item -ItemType Directory -Force -Path $LibDir | Out-Null
Write-Output "sketchbook libraries: $LibDir"

# ---------------------------------------------------------------------------
# 1. RemoteACCore - already an Arduino library (library.properties + src\)
# ---------------------------------------------------------------------------
$CoreSrc = Join-Path $RepoRoot 'firmware\shared\RemoteACCore'
$CoreDst = Join-Path $LibDir 'RemoteACCore'
if (Test-Path -LiteralPath $CoreDst) {
    Remove-Item -LiteralPath $CoreDst -Recurse -Force
}
try {
    New-Item -ItemType Junction -Path $CoreDst -Target $CoreSrc | Out-Null
    Write-Output "linked   RemoteACCore -> $CoreSrc"
} catch {
    Copy-Item -LiteralPath $CoreSrc -Destination $CoreDst -Recurse -Force
    Write-Output 'copied   RemoteACCore (junction unavailable; re-run after editing the repo)'
}

# ---------------------------------------------------------------------------
# 2. srun-c - generated by the single, deterministic adapter script
# ---------------------------------------------------------------------------
# tools\prepare_srun_arduino_library.py is the ONLY place that knows how to turn
# the authoritative PlatformIO layout into an Arduino library. It validates the
# source inventory, preserves the licence, writes a THIRD_PARTY_NOTICE and emits
# a SHA256 MANIFEST.json. Python is already required by the ESP8266 core
# (mkbuildoptglobals.py), so this adds no new dependency.
$python = $env:PYTHON
if (-not $python) {
    foreach ($candidate in @('python3', 'python')) {
        if (Get-Command $candidate -ErrorAction SilentlyContinue) { $python = $candidate; break }
    }
}
if (-not $python) {
    throw 'python not found; it is required to generate the srun-c Arduino library'
}
& $python (Join-Path $RepoRoot 'tools\prepare_srun_arduino_library.py') --output $LibDir
if ($LASTEXITCODE -ne 0) { throw "prepare_srun_arduino_library.py failed ($LASTEXITCODE)" }
Write-Output "generated srun-c    -> $(Join-Path $LibDir 'srun-c')"

Write-Output ''
Write-Output 'Installed libraries:'
Get-ChildItem -LiteralPath $LibDir -Name | ForEach-Object { Write-Output "  $_" }
Write-Output ''
Write-Output 'Still required from the Library Manager (exact versions):'
Write-Output '  DHT sensor library 1.4.7'
Write-Output '  Adafruit Unified Sensor 1.1.15'
Write-Output '  PubSubClient 2.8.0'
Write-Output '  ArduinoJson 6.21.5'
