#!/usr/bin/env bash
#
# install-arduino-libraries.sh — make the two repository libraries visible to
# the Arduino IDE / arduino-cli.
#
# The Arduino IDE only looks for libraries inside your sketchbook
# (<sketchbook>/libraries). This repository keeps a single authoritative copy of
# each library:
#
#   firmware/shared/RemoteACCore          Arduino library layout already
#   firmware/agent-platformio/lib/srun-c  PlatformIO layout (include/ + src/)
#
# RemoteACCore is symlinked, so editing the repository (for example dropping
# your own config/profiles/xidian.h) is picked up immediately.
# srun-c must be flattened into a single src/ directory because arduino-cli does
# not understand the PlatformIO include/ + src/ split, so it is generated. Re-run
# this script after changing anything under lib/srun-c.
#
# Usage:
#   ./firmware/arduino-ide/tools/install-arduino-libraries.sh
#   ARDUINO_SKETCHBOOK=/custom/path ./firmware/arduino-ide/tools/install-arduino-libraries.sh
#
# This script never touches credentials, never compiles, never flashes.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
SKETCHBOOK="${ARDUINO_SKETCHBOOK:-$HOME/Arduino}"
LIBDIR="$SKETCHBOOK/libraries"

mkdir -p "$LIBDIR"
echo "sketchbook libraries: $LIBDIR"

# ---------------------------------------------------------------------------
# 1. RemoteACCore — already an Arduino library (library.properties + src/)
# ---------------------------------------------------------------------------
CORE_SRC="$REPO_ROOT/firmware/shared/RemoteACCore"
CORE_DST="$LIBDIR/RemoteACCore"
rm -rf "$CORE_DST"
if ln -s "$CORE_SRC" "$CORE_DST" 2>/dev/null; then
  echo "linked   RemoteACCore -> $CORE_SRC"
else
  cp -R "$CORE_SRC" "$CORE_DST"
  echo "copied   RemoteACCore (symlink unavailable; re-run after editing the repo)"
fi

# ---------------------------------------------------------------------------
# 2. srun-c — generated by the single, deterministic adapter script
# ---------------------------------------------------------------------------
# tools/prepare_srun_arduino_library.py is the ONLY place that knows how to turn
# the authoritative PlatformIO layout into an Arduino library. It validates the
# source inventory, preserves the licence, writes a THIRD_PARTY_NOTICE and emits
# a SHA256 MANIFEST.json. Python is already required by the ESP8266 core
# (mkbuildoptglobals.py), so this adds no new dependency.
PY="${PYTHON:-}"
if [ -z "$PY" ]; then
  if command -v python3 >/dev/null 2>&1; then PY=python3
  elif command -v python >/dev/null 2>&1; then PY=python
  else
    echo "ERROR: python3 not found; it is required to generate the srun-c Arduino library" >&2
    exit 1
  fi
fi
"$PY" "$REPO_ROOT/tools/prepare_srun_arduino_library.py" --output "$LIBDIR"
echo "generated srun-c    -> $LIBDIR/srun-c"

echo
echo "Installed libraries:"
ls -1 "$LIBDIR"
echo
echo "Still required from the Library Manager (exact versions):"
echo "  DHT sensor library 1.4.7"
echo "  Adafruit Unified Sensor 1.1.15"
echo "  PubSubClient 2.8.0"
echo "  ArduinoJson 6.21.5"
