"""Public AC state capture presets for the IR learning tool.

The actual preset count is len(PRESETS); do not hardcode a number in the
docstring. This file must stay byte-identical with its counterpart copy in
the repository (see tools/check-public-docs.py for the drift check)."""
PRESETS = [
    {"name": "关机", "codeId": "hisense_power_off_v1",
     "power": "off", "mode": "cool", "temp": "24", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "unknown", "swingH": "unknown"},
    {"name": "制冷24℃ 超强风 上下扫风 左右扫风", "codeId": "hisense_cool_24_turbo_swingVH_v1",
     "power": "on", "mode": "cool", "temp": "24", "fan": "turbo",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "on", "swingH": "on"},
    {"name": "制冷20℃ 超强风 上下扫风 左右扫风", "codeId": "hisense_cool_20_turbo_swingVH_v1",
     "power": "on", "mode": "cool", "temp": "20", "fan": "turbo",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "on", "swingH": "on"},
    {"name": "制冷25℃ 自动风 上下扫风 左右扫风", "codeId": "hisense_cool_25_auto_swingVH_v1",
     "power": "on", "mode": "cool", "temp": "25", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "on", "swingH": "on"},
    {"name": "制冷26℃ 自动风 上下扫风 左右扫风", "codeId": "hisense_cool_26_auto_swingVH_v1",
     "power": "on", "mode": "cool", "temp": "26", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "on", "swingH": "on"},
    {"name": "除湿24℃ 超强风 上下扫风 左右扫风", "codeId": "hisense_dry_24_turbo_swingVH_v1",
     "power": "on", "mode": "dry", "temp": "24", "fan": "turbo",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "on", "swingH": "on"},
    {"name": "除湿24℃ 自动风 上下扫风 左右扫风", "codeId": "hisense_dry_24_auto_swingVH_v1",
     "power": "on", "mode": "dry", "temp": "24", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "on", "swingH": "on"},
    {"name": "除湿24℃ 静音风 上下扫风 左右扫风", "codeId": "hisense_dry_24_silent_swingVH_v1",
     "power": "on", "mode": "dry", "temp": "24", "fan": "silent",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "on", "swingH": "on"},
    {"name": "制热26℃ 自动风 上下扫风 左右扫风", "codeId": "hisense_heat_26_auto_swingVH_v1",
     "power": "on", "mode": "heat", "temp": "26", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "on", "swingH": "on"},
    {"name": "制热28℃ 自动风 上下扫风 左右扫风", "codeId": "hisense_heat_28_auto_swingVH_v1",
     "power": "on", "mode": "heat", "temp": "28", "fan": "auto",
     "turbo": False, "quiet": False, "sleep": False,
     "swingV": "on", "swingH": "on"},
]
