#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen-wifi-ssid-cases.py — generate the C++ SSID test vectors from the shared JSON.

The single source of truth is test/fixtures/wifi_ssid_validation_cases.json.
Python's parity test (tools/test-wifi-ssid-parity.py) reads it directly; this
script emits test/host/wifi_ssid_cases.inc which test_wifi_ssid_validation.cpp
compiles. Deterministic output: same JSON -> same .inc.

Usage:
  gen-wifi-ssid-cases.py            write test/host/wifi_ssid_cases.inc
  gen-wifi-ssid-cases.py --check    exit non-zero if the .inc is stale
"""
import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIXTURE = os.path.join(ROOT, "test", "fixtures", "wifi_ssid_validation_cases.json")
OUTPUT = os.path.join(ROOT, "test", "host", "wifi_ssid_cases.inc")


def c_string_escape(s):
    """Escape a decoded string for a C string literal.

    JSON already decoded \\uXXXX escapes, so the string may contain raw
    control characters. C++ string literals MUST NOT contain an unescaped
    newline, and control bytes should be \\xNN for readability.
    """
    out = []
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif o < 0x20 or o == 0x7F:
            out.append("\\x%02x" % o)
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def render(fixture_path):
    with open(fixture_path, encoding="utf-8") as f:
        data = json.load(f)
    cases = data["cases"]
    lines = []
    lines.append("// AUTO-GENERATED by tools/gen-wifi-ssid-cases.py from")
    lines.append("// test/fixtures/wifi_ssid_validation_cases.json — DO NOT EDIT.")
    lines.append("// Regenerate with: python tools/gen-wifi-ssid-cases.py")
    lines.append("//")
    lines.append("struct WifiSsidCase {")
    lines.append("  const char* name;")
    lines.append("  const char* ssid;      // nullptr for the nullptr case")
    lines.append("  bool expectedValid;")
    lines.append("  WifiSsidValidationCode expectedCode;")
    lines.append("};")
    lines.append("")
    lines.append("static const WifiSsidCase kWifiSsidCases[] = {")
    for c in cases:
        name = c_string_escape(c["name"])
        if c["ssid"] is None:
            ssid = "nullptr"
        else:
            ssid = c_string_escape(c["ssid"])
        valid = "true" if c["expectedValid"] else "false"
        code = c["expectedCode"]
        lines.append("  { %s, %s, %s, %s }," % (name, ssid, valid, code))
    lines.append("};")
    lines.append("")
    lines.append("static const int kWifiSsidCaseCount = %d;" % len(cases))
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ns = ap.parse_args()
    rendered = render(FIXTURE)
    if ns.check:
        if not os.path.exists(OUTPUT):
            print("SSID_CASES_INC_STALE=True (missing)")
            return 1
        with open(OUTPUT, encoding="utf-8") as f:
            current = f.read()
        if current != rendered:
            print("SSID_CASES_INC_STALE=True")
            return 1
        print("SSID_CASES_INC_STALE=False")
        return 0
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(rendered)
    print("WIFI_SSID_CASES_GENERATED=%s" % OUTPUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
