#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""自动从候选 002.bin 生成 PROGMEM C 数组（§四 固化）。

设计原则（用户指令 §四 / §十六）：
  - 零手工转录：字节完全由 002.bin 读取生成。
  - 交叉核对 capture_manifest.csv / *.json 中的 bin_sha256（完整 SHA），不一致即失败。
  - 整帧固化：保存的是 COMPLETE 22H 帧（68..16），不是只保存 DATA 域。
  - roundtrip 校验：生成 .cpp 后解析其数组，逐字节比对 002.bin 与 SHA256；
    并反向导出 BIN 再比对，确保 PROGMEM 与源文件字节一致。
  - 输出文件受 ENABLE_IR_MUTATING_COMMANDS 守卫：公开构建（=0）不含私有红外码（§四）。

生成文件（用户 §四 指定路径/命名）：
  src/private_ir_codes/hisense_cool24_quiet_swing_both_on.h
  src/private_ir_codes/hisense_cool24_quiet_swing_both_on.cpp
"""
import sys
import os
import re
import json
import hashlib
import csv

PROJECT_ROOT = r"C:\example\remote-ac"
REF_IR = os.path.join(PROJECT_ROOT, "References", "IR")
CAPTURES = os.path.join(REF_IR, "captures")
IR_CODES_DIR = os.path.join(PROJECT_ROOT, "Firmware", "Remote_AC_Controller", "src", "private_ir_codes")

CANDIDATE_BIN = "HISENSE_COOL_24_QUIET_SWING_V_ON_SWING_H_ON_POWER_ON_CAPTURE_002.bin"
CANDIDATE_JSON = "HISENSE_COOL_24_QUIET_SWING_V_ON_SWING_H_ON_POWER_ON_CAPTURE_002.json"
MANIFEST_CSV = "capture_manifest.csv"
CSV_ROW_KEY = "HISENSE_COOL_24_QUIET_SWING_V_ON_SWING_H_ON_POWER_ON_CAPTURE_002"

CODE_ID = "hisense_cool_24_quiet_swing_v_on_swing_h_on_power_on_v1"
HEADER_GUARD = "HISENSE_COOL24_QUIET_SWING_BOTH_ON_H"
SYMBOL = "kHisenseCool24QuietSwingBothOn"


def fail(msg):
    print("GEN_FAIL: " + msg)
    sys.exit(1)


def read_manifest_sha():
    """Return set of manifest SHA strings for 002 (from CSV + JSON). Empty if none."""
    shas = set()
    # CSV
    csv_path = os.path.join(CAPTURES, MANIFEST_CSV)
    if os.path.exists(csv_path):
        with open(csv_path, "r", encoding="utf-8-sig", newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                if row.get("capture_id") == CSV_ROW_KEY and row.get("bin_sha256"):
                    shas.add(row["bin_sha256"].strip().lower())
    # JSON
    json_path = os.path.join(CAPTURES, CANDIDATE_JSON)
    if os.path.exists(json_path):
        try:
            js = json.load(open(json_path, encoding="utf-8"))
            if js.get("bin_sha256"):
                shas.add(js["bin_sha256"].strip().lower())
        except Exception:
            pass
    return shas


def main():
    bin_path = os.path.join(CAPTURES, CANDIDATE_BIN)
    if not os.path.exists(bin_path):
        fail("候选 BIN 不存在: " + bin_path)
    data = open(bin_path, "rb").read()
    n = len(data)
    sha = hashlib.sha256(data).hexdigest()

    # 交叉核对 manifest 完整 SHA
    manifest_shas = read_manifest_sha()
    if manifest_shas and sha.lower() not in manifest_shas:
        fail("SHA 不一致: 计算得到 %s, manifest=%s" % (sha, ",".join(sorted(manifest_shas))))
    if n != 418:
        fail("长度不符预期 418: 实际 %d" % n)
    # 结构校验：首字节 0x68 / 尾字节 0x16 / LEN 字段匹配 / CS 校验
    if data[0] != 0x68:
        fail("首字节非 0x68: 0x%02X" % data[0])
    if data[n - 1] != 0x16:
        fail("尾字节非 0x16: 0x%02X" % data[n - 1])
    total = data[1] | (data[2] << 8)
    if total != n:
        fail("LEN 字段 %d != 实际长度 %d" % (total, n))
    if data[3] != 0x00:
        fail("ADDR 非 0x00: 0x%02X" % data[3])
    if data[4] != 0x22:
        fail("AFN 非 0x22: 0x%02X" % data[4])
    csum = (sum(data[3:n - 2]) & 0xFF)
    if csum != data[n - 2]:
        fail("CS 校验失败: 计算 0x%02X, 帧内 0x%02X" % (csum, data[n - 2]))

    os.makedirs(IR_CODES_DIR, exist_ok=True)

    # ---- 生成 .h ----
    h_path = os.path.join(IR_CODES_DIR, "hisense_cool24_quiet_swing_both_on.h")
    h_lines = []
    h_lines.append("// AUTO-GENERATED by tools/gen_ir_code.py — DO NOT EDIT BY HAND.")
    h_lines.append("// Source: References/IR/captures/%s" % CANDIDATE_BIN)
    h_lines.append("// SHA256: %s" % sha)
    h_lines.append("// Length: %d" % n)
    h_lines.append("// Structure: COMPLETE 22H UART frame (68..16). AFN=0x22 external-code replay.")
    h_lines.append("#pragma once")
    h_lines.append("")
    h_lines.append("#include <Arduino.h>")
    h_lines.append("")
    h_lines.append("#if ENABLE_IR_MUTATING_COMMANDS")
    h_lines.append("// 固化到 ESP8266 Flash 的只读海信开机红外码（PROGMEM，整帧）。")
    h_lines.append("// 仅私有/ir-lab 生产构建包含（ENABLE_IR_MUTATING_COMMANDS=1）；公开构建不含（§四）。")
    h_lines.append("extern const uint8_t %s[] PROGMEM;" % SYMBOL)
    h_lines.append("extern const uint16_t %sLen;" % SYMBOL)
    h_lines.append("extern const uint16_t %sExpectedLen;" % SYMBOL)
    h_lines.append("extern const char* %sId;" % SYMBOL)
    h_lines.append("extern const char* %sSha256;" % SYMBOL)
    h_lines.append("#endif // ENABLE_IR_MUTATING_COMMANDS")
    h_lines.append("")
    open(h_path, "w", encoding="utf-8").write("\n".join(h_lines))

    # ---- 生成 .cpp（字节分 12 个一行）----
    cpp_path = os.path.join(IR_CODES_DIR, "hisense_cool24_quiet_swing_both_on.cpp")
    cpp_lines = []
    cpp_lines.append("// AUTO-GENERATED by tools/gen_ir_code.py — DO NOT EDIT BY HAND.")
    cpp_lines.append("// Source: References/IR/captures/%s" % CANDIDATE_BIN)
    cpp_lines.append("// SHA256: %s" % sha)
    cpp_lines.append("// Length: %d" % n)
    cpp_lines.append("#include <Arduino.h>")
    cpp_lines.append('#include "private_ir_codes/hisense_cool24_quiet_swing_both_on.h"')
    cpp_lines.append("")
    cpp_lines.append("#if ENABLE_IR_MUTATING_COMMANDS")
    cpp_lines.append("")
    cpp_lines.append("// 固化红外码（ZJ-IR-V2 外部码 AFN=0x22 帧，68..16 整帧，原样回传即发射）。")
    cpp_lines.append("const uint8_t %s[] PROGMEM = {" % SYMBOL)
    per = 12
    for i in range(0, n, per):
        chunk = data[i:i + per]
        hexvals = ", ".join("0x%02X" % b for b in chunk)
        cpp_lines.append("  " + hexvals + ",")
    cpp_lines.append("};")
    cpp_lines.append("")
    cpp_lines.append("const uint16_t %sLen = %d;" % (SYMBOL, n))
    cpp_lines.append("const uint16_t %sExpectedLen = %d;" % (SYMBOL, n))
    cpp_lines.append('const char* %sId = "%s";' % (SYMBOL, CODE_ID))
    cpp_lines.append('const char* %sSha256 = "%s";' % (SYMBOL, sha))
    cpp_lines.append("")
    cpp_lines.append("#endif // ENABLE_IR_MUTATING_COMMANDS")
    cpp_lines.append("")
    open(cpp_path, "w", encoding="utf-8").write("\n".join(cpp_lines))

    print("GEN_HEADER=%s" % h_path)
    print("GEN_SOURCE=%s" % cpp_path)
    print("IR_CODE_002_ID=%s" % CODE_ID)
    print("IR_CODE_002_LENGTH=%d" % n)
    print("IR_CODE_002_SHA256=%s" % sha)
    print("IR_CODE_002_MANIFEST_SHA_MATCH=%s" % ("TRUE" if manifest_shas else "N/A"))

    # ---- roundtrip 校验：解析生成的 .cpp 数组，逐字节比对 ----
    text = open(cpp_path, "r", encoding="utf-8").read()
    m = re.search(r"const uint8_t %s\[\] PROGMEM = \{(.*?)\};" % re.escape(SYMBOL), text, re.S)
    if not m:
        fail("roundtrip: 无法从生成的 .cpp 解析数组")
    body = m.group(1)
    vals = re.findall(r"0x([0-9A-Fa-f]{2})", body)
    gen = bytes(int(v, 16) for v in vals)
    if gen != data:
        fail("roundtrip: 生成数组与 002.bin 字节不一致 (len gen=%d data=%d)" % (len(gen), len(data)))
    if hashlib.sha256(gen).hexdigest() != sha:
        fail("roundtrip: 生成数组 SHA 不一致")

    # ---- 反向导出 BIN 再比对（§四 要求 reverse-export test BIN）----
    rev_bin = os.path.join(IR_CODES_DIR, "_reverse_export_002.bin")
    open(rev_bin, "wb").write(gen)
    if hashlib.sha256(open(rev_bin, "rb").read()).hexdigest() != sha:
        fail("reverse-export BIN SHA 不一致")
    os.remove(rev_bin)

    print("IR_CODE_002_FULL_22H_FRAME=True")
    print("IR_CODE_002_ROUNDTRIP_PASS=True")
    print("IR_CODE_002_REVERSE_EXPORT_PASS=True")
    print("IR_CODE_002_GENERATED_PASS=True")


if __name__ == "__main__":
    main()
